name: Deno

on:
  push:
    branches: ["main"]
    paths:
      - '**.js'
  pull_request:
    branches: ["main"]
    paths:
      - '**.js'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint script.js
      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
